name: variant-pipeline
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  # Required packages
  - fastqc=0.11.9
  - bwa=0.7.17
  - picard=2.27.5
  - multiqc=1.12
  - gatk4=4.1.9.0
  - snpeff=4.3g       # includes SnpSift
  - bcftools=1.14

  # Optional/Extras
  - samtools=1.15.1
  - bedtools=2.30.0

# CLI Command to create the enviroment: conda env create -f conda_enviroment.yml